namespace EpiFlow.UnitTests
{
    public static class StaticTestData
    {
        public const string SuperLongString = @"Bacon ipsum dolor amet tail drumstick ground round doner pastrami strip steak. Prosciutto kielbasa capicola ball tip. Pork chop ball tip ribeye, ground round short loin prosciutto drumstick fatback pork belly beef ribs. Leberkas ribeye ham hock prosciutto, cupim corned beef bresaola. Andouille cupim flank, landjaeger boudin ground round tail sausage pastrami t-bone corned beef pork chop fatback meatball sirloin. Doner porchetta flank rump, salami shank bresaola short loin frankfurter kielbasa hamburger. Spare ribs corned beef brisket ham hock pork belly ground round venison leberkas.

Pork loin ham hock shank, frankfurter rump turkey short loin.Filet mignon short ribs prosciutto, hamburger tenderloin drumstick tongue shankle.Jerky capicola shank ham hock cupim landjaeger, t-bone pork belly tri-tip alcatra frankfurter corned beef swine sausage turducken. Jerky frankfurter tail beef bresaola tongue. Pastrami brisket pork chop, ribeye filet mignon prosciutto doner sirloin andouille corned beef pork belly.Kevin porchetta flank tri-tip cow turkey pig bacon hamburger sausage beef. Sirloin ball tip jerky biltong, porchetta pork belly corned beef ribeye fatback shoulder sausage.

Flank kevin tenderloin sausage bresaola.Pastrami pork belly hamburger, sausage corned beef prosciutto rump ball tip meatloaf andouille.Swine flank biltong porchetta pastrami shankle fatback.Frankfurter flank meatloaf, cow jerky drumstick leberkas jowl.Tenderloin strip steak ball tip kevin salami.Turkey short loin hamburger swine pork, pork chop corned beef boudin pig rump tongue short ribs andouille tenderloin. Tail fatback tri-tip shoulder prosciutto cupim turkey venison pork belly pastrami corned beef swine tenderloin.

Pastrami frankfurter venison alcatra short ribs andouille shankle. Short loin jerky jowl shank, biltong chuck ball tip ribeye tenderloin hamburger bresaola tongue kielbasa chicken.Leberkas sirloin frankfurter rump pig flank. Meatloaf shankle sausage swine. Andouille corned beef brisket, landjaeger porchetta rump drumstick sausage pig strip steak biltong picanha ham hock alcatra.Tenderloin turducken ham hock filet mignon cupim prosciutto tail short ribs salami picanha corned beef doner short loin.

Turkey andouille biltong kielbasa bresaola ribeye rump cupim tenderloin shoulder short loin hamburger sirloin pork.Tongue pork loin turducken, ground round cow biltong ham boudin meatball rump. Pork chop swine biltong shoulder bresaola hamburger, tenderloin sausage turkey landjaeger chicken filet mignon.Kevin cupim strip steak ground round. Cow ball tip short loin capicola swine chuck turkey salami prosciutto spare ribs shoulder.Andouille rump bacon shoulder hamburger boudin pork chop.

Venison chicken pork chop, picanha spare ribs landjaeger tri-tip kevin andouille sirloin ham hock short ribs. Drumstick pork loin ground round, jowl chicken kielbasa porchetta brisket shoulder. Corned beef hamburger ground round pork bresaola, ham venison bacon jerky kielbasa alcatra frankfurter.Ground round porchetta rump corned beef filet mignon meatball pancetta tongue shankle chicken capicola swine kevin salami pork. Pastrami pork ham jerky cow picanha shank boudin tongue prosciutto t-bone ball tip turkey short ribs beef.Pork t-bone turducken turkey.

Jowl chicken boudin pork loin.Bacon short ribs jerky frankfurter, chuck ribeye tongue flank shankle capicola ball tip leberkas ham hock alcatra. Ribeye biltong pork loin ball tip frankfurter t-bone corned beef beef strip steak short ribs meatball.Salami doner shankle spare ribs sausage kevin capicola drumstick pork belly corned beef tail kielbasa picanha ball tip pork loin. Cow ham hock spare ribs short ribs chuck andouille beef ribs tail.Alcatra bresaola cupim cow turducken, frankfurter short ribs beef ham hock corned beef andouille. Spare ribs flank landjaeger doner, sausage sirloin tail beef ribs short ribs brisket.

Porchetta ribeye flank biltong jowl.Corned beef chicken t-bone meatball strip steak short ribs. Beef ribs fatback landjaeger ball tip. Ball tip bacon ribeye spare ribs frankfurter shankle hamburger landjaeger prosciutto venison pork belly jerky.

Chuck tri-tip biltong tongue.Beef ribs ham pork beef boudin ground round hamburger tongue jowl.Chuck sausage spare ribs landjaeger turkey cupim t-bone filet mignon pastrami pork.Filet mignon brisket boudin swine leberkas turducken kielbasa meatball cupim chuck fatback salami pork alcatra sirloin. Pork pork belly frankfurter jerky prosciutto tail, tenderloin salami pig porchetta pork loin picanha boudin bacon beef. Strip steak jerky fatback turkey sirloin bacon short loin frankfurter alcatra ball tip meatloaf shoulder flank tongue. Sirloin pig pork chop turducken pork doner.

Brisket t-bone shankle tenderloin strip steak jerky biltong beef ribs turkey. Brisket drumstick flank turkey strip steak pork pastrami shoulder bresaola sirloin chicken landjaeger rump alcatra.Jerky flank sausage ribeye pork belly. Pastrami leberkas meatloaf, drumstick tenderloin spare ribs andouille doner short loin t-bone turkey swine beef. Sausage bresaola andouille biltong, corned beef strip steak venison pig landjaeger.

Cow tri-tip ham tenderloin venison. Kevin tongue pork belly turkey, pork sausage prosciutto shank kielbasa flank pancetta filet mignon salami picanha.Pastrami kevin capicola, t-bone turkey pork belly spare ribs picanha alcatra strip steak shoulder.Filet mignon fatback ham hock pancetta tenderloin jowl porchetta sausage. Beef short loin shankle landjaeger, filet mignon short ribs tri-tip ribeye rump ground round t-bone venison doner.Turkey bresaola sirloin meatball pork.

Filet mignon frankfurter corned beef sirloin tail pastrami ground round, kielbasa alcatra tongue spare ribs pig chuck.Meatloaf frankfurter tri-tip turkey. Spare ribs strip steak tail corned beef ball tip chicken turducken.Shank kielbasa bacon, ball tip venison short ribs ham.Frankfurter ham tail ribeye, tri-tip beef ribs sirloin bacon pork loin boudin fatback kielbasa filet mignon shoulder.Turkey ham pancetta ribeye beef.

Tenderloin kevin cupim tongue ham hock brisket bresaola meatball rump. Chuck meatball shoulder, swine ribeye doner salami tri-tip tenderloin pork belly landjaeger.Tail rump kielbasa drumstick, strip steak short ribs chuck.Turkey prosciutto landjaeger beef ribs pork loin meatloaf.

Fatback t-bone short ribs chuck.Venison tongue porchetta ham bresaola.Short loin drumstick biltong short ribs shoulder corned beef landjaeger kevin filet mignon brisket. Pork loin frankfurter meatloaf capicola, t-bone ground round bresaola. Tail brisket salami fatback, sausage drumstick ham hock swine beef boudin bresaola pancetta jerky. Ham hock boudin sirloin ball tip short loin rump picanha t-bone tri-tip landjaeger tail kielbasa.

Turkey landjaeger flank, beef meatloaf pancetta porchetta swine filet mignon.Short loin pastrami strip steak rump. Fatback shoulder hamburger leberkas shank boudin spare ribs venison pork cow bacon flank.Cupim turducken filet mignon, tail meatloaf corned beef beef ribs kielbasa doner porchetta ham.

Tri-tip bacon shankle cow ball tip ham venison pork brisket pastrami pork chop alcatra sirloin hamburger short loin. Beef hamburger kielbasa ground round pork belly, pig cupim salami strip steak pork. Turkey turducken picanha, prosciutto cupim ham hock pig boudin drumstick shankle short loin tongue.Beef turducken meatloaf, capicola pig brisket pork chop filet mignon ham tongue tenderloin spare ribs landjaeger swine doner.Bresaola swine beef ribs shank kevin. Hamburger pork boudin rump. Doner pork belly strip steak, jowl ham hock tri-tip capicola pastrami beef cupim pork chop tenderloin.

Cow fatback swine meatloaf doner kielbasa prosciutto boudin porchetta kevin shankle turkey brisket rump corned beef. Meatloaf chuck beef ribs shoulder shank. Turkey swine tri-tip short ribs sausage brisket alcatra picanha ham bresaola boudin chicken corned beef rump tail. Venison fatback picanha kielbasa shank chuck ham hock bresaola meatball rump capicola salami.Tri-tip ribeye filet mignon turducken bacon. Bacon kielbasa shank sirloin fatback doner biltong flank prosciutto hamburger ball tip filet mignon pastrami.

Meatball chicken kielbasa, pork chop frankfurter strip steak cow pastrami boudin. Chuck jerky ham hock corned beef spare ribs pork belly prosciutto drumstick flank sausage frankfurter.Beef picanha fatback, shank ground round doner cow meatloaf pork belly boudin.Turducken strip steak ball tip leberkas bresaola ham hock.

Spare ribs prosciutto jerky pancetta jowl turkey.Brisket corned beef shoulder chuck doner. Brisket bresaola ground round spare ribs ham hock chuck pork belly.Ground round alcatra sirloin rump leberkas, pork belly frankfurter short ribs drumstick turducken ham turkey. Ball tip fatback prosciutto corned beef shankle salami pig ham hock cow pastrami meatloaf jowl.Bresaola ribeye ham pork belly, ham hock chicken sausage rump porchetta chuck.Short loin bresaola kielbasa frankfurter.

Ham boudin pig pork chop venison porchetta.Spare ribs salami ball tip alcatra rump.Leberkas ham hock shoulder t-bone doner ground round, cow tail. T-bone drumstick andouille tenderloin tail jowl ball tip kevin.Strip steak shoulder beef ribs shankle picanha pork chop.Pork loin chicken turkey doner ham hock hamburger pork chop jerky corned beef.

Short loin frankfurter tenderloin, hamburger biltong swine shank ham hock pig tongue spare ribs porchetta.Hamburger drumstick jowl kielbasa sausage t-bone shankle corned beef andouille landjaeger doner meatball kevin tongue shoulder.Turkey ground round corned beef, chuck swine sirloin turducken tail brisket pork chicken strip steak hamburger.Ham pig turducken filet mignon frankfurter short ribs, short loin strip steak corned beef capicola pork chop hamburger cupim.

Corned beef ham ham hock sausage capicola strip steak tri-tip, short ribs jowl chuck. Pig beef t-bone, meatball doner kielbasa ham. Short loin andouille prosciutto spare ribs, pork cow salami.Sausage short ribs ham hock kielbasa flank sirloin alcatra drumstick ribeye. T-bone chicken turkey rump pork loin kielbasa.Rump pancetta sausage boudin alcatra ham tail jerky hamburger pork chop.

Turkey short ribs corned beef andouille, biltong tail chuck ground round.Swine biltong short ribs capicola.Ball tip kielbasa venison pork fatback. Ham hock cow turkey, sirloin ribeye ground round chicken kevin andouille alcatra short ribs flank brisket turducken shankle. Beef ribs t-bone chicken, pig pork sirloin doner jowl drumstick venison spare ribs kevin bresaola short ribs.

Hamburger bacon shoulder, prosciutto ground round tenderloin beef pastrami andouille t-bone.Pig t-bone meatloaf shank pork, flank beef ribs shoulder tongue ham capicola tri-tip brisket. Ground round turkey picanha, fatback venison hamburger beef ribs andouille meatball pork jerky leberkas doner.Beef ribs drumstick pastrami brisket bacon tail pancetta jerky shoulder sausage.Drumstick landjaeger sausage shank kielbasa brisket, corned beef jerky beef ribs rump short loin kevin.

Cupim hamburger venison capicola ham.Turducken bacon landjaeger pancetta turkey cupim. Pork chop boudin ground round chuck jowl.Short loin meatball swine ribeye, meatloaf porchetta sirloin pork chop hamburger fatback tenderloin corned beef tongue.T-bone shoulder bresaola kevin ribeye.Sausage turkey jowl filet mignon.T-bone venison pork chop filet mignon pork loin meatloaf drumstick frankfurter short loin, tail pork cupim.

Landjaeger ribeye frankfurter, pancetta rump short loin alcatra shank pig tri-tip.Prosciutto doner jerky drumstick andouille pork belly cupim pork venison salami.Salami pork chop cow ball tip sausage corned beef jerky spare ribs. Filet mignon kielbasa fatback corned beef, sausage sirloin hamburger drumstick pork belly meatloaf.Jerky venison short ribs ribeye.Landjaeger ribeye hamburger, turducken chicken jerky filet mignon t-bone.Doner biltong beef turducken, jerky short ribs pork chop pork loin drumstick jowl bacon.

Bacon meatball bresaola kevin t-bone shank corned beef ham hock leberkas short loin cupim.Picanha cupim bresaola ribeye shank porchetta meatloaf.Pork chop bresaola cupim, beef ribs leberkas landjaeger turkey shankle sausage.Swine shank pork loin pork chop. Corned beef frankfurter cow, shoulder alcatra brisket ball tip shank tail.Shoulder capicola pastrami bresaola pancetta.

Rump pork belly alcatra, pancetta leberkas fatback t-bone hamburger picanha.Frankfurter chicken shankle, cow fatback andouille pancetta pastrami shoulder meatloaf brisket tri-tip ball tip.Pork loin biltong ribeye, bacon rump ground round hamburger venison bresaola swine. Beef leberkas alcatra tri-tip fatback sausage ham spare ribs drumstick kevin boudin andouille.

Picanha brisket ham shank flank, tail salami meatball doner beef cow meatloaf bresaola kevin.Rump sausage jerky, ham biltong cupim pork shankle chuck tri-tip porchetta hamburger alcatra t-bone.Short loin meatloaf chicken beef tongue, tenderloin bresaola prosciutto doner ham hock. Flank jowl pork chop venison beef ribs tail brisket hamburger kielbasa ham capicola turducken. Short ribs meatloaf andouille kielbasa swine bresaola.

Beef chuck flank, capicola meatloaf turkey prosciutto drumstick cupim sausage tongue kevin alcatra pastrami.Porchetta hamburger kielbasa corned beef landjaeger pork biltong spare ribs pork loin drumstick.Pig landjaeger tongue pork belly picanha ball tip, sirloin turkey jowl pork chop tenderloin cow.Ball tip pig hamburger tongue brisket ribeye tail biltong beef ribs filet mignon meatball, flank pork belly t-bone.Rump ball tip tongue jowl venison ham hock jerky bresaola. Picanha turkey meatloaf kielbasa. Shoulder drumstick tail short ribs, sirloin shank pastrami meatloaf.

Meatloaf kielbasa pastrami, bacon boudin porchetta jerky prosciutto rump bresaola salami meatball alcatra strip steak. Chuck chicken alcatra capicola shankle, boudin short ribs pig sausage beef ribs brisket landjaeger pork belly. Leberkas chuck pig prosciutto beef strip steak cupim shankle jerky pork sirloin boudin picanha swine.Ham hock jowl pork loin, andouille picanha ball tip tongue cow chuck fatback t-bone ground round chicken. Pork loin spare ribs pork belly, boudin chicken capicola tenderloin biltong tri-tip beef ribs picanha ground round. Short loin ball tip t-bone cupim fatback, strip steak leberkas boudin ground round filet mignon porchetta turkey.

Pancetta beef ribs chuck shank alcatra brisket turkey bacon short loin shoulder.Tail tongue picanha landjaeger drumstick doner flank turkey corned beef sausage ground round pig short loin leberkas.Short ribs pastrami pork chop drumstick corned beef ham hock capicola.Turducken strip steak andouille picanha bacon shankle rump brisket pork chop.Kielbasa landjaeger turkey pork loin shankle brisket.

Meatball salami venison, kevin tri-tip ground round bacon. Ball tip flank kielbasa cow short loin, short ribs leberkas beef hamburger tail pork chop. Shankle pancetta turkey tri-tip fatback flank.Turkey filet mignon capicola pork belly, t-bone brisket pancetta frankfurter landjaeger sausage short ribs short loin kevin jerky ground round. Turkey ball tip pork swine short ribs corned beef.

Ball tip bacon alcatra filet mignon, kielbasa shank pork loin ham hock brisket biltong bresaola tenderloin ground round shankle strip steak.Spare ribs meatball strip steak meatloaf. Brisket shoulder ham, short loin ground round venison ball tip jerky tail rump swine biltong porchetta.Chicken corned beef drumstick kielbasa.Ham salami brisket, meatball bacon pork spare ribs shoulder short loin short ribs doner tongue beef ribs andouille fatback.

Short loin porchetta meatball meatloaf pork belly sausage. Corned beef brisket tenderloin alcatra, landjaeger prosciutto andouille cupim salami ham hock.Salami sausage fatback beef, pork loin pancetta chuck beef ribs chicken shankle capicola drumstick andouille.Chicken short loin sausage drumstick. Chicken hamburger bacon shankle tenderloin.Drumstick shankle cupim pork loin, cow jerky andouille pancetta porchetta t-bone alcatra beef ribs.

Pig filet mignon pork loin, beef short loin doner prosciutto hamburger porchetta tri-tip cow drumstick brisket pork.Pastrami short loin flank kielbasa tongue.Pork belly prosciutto beef, drumstick venison chuck tenderloin pork loin ham hock. Prosciutto shankle alcatra boudin turkey.

Ground round frankfurter beef ribs chuck jowl tenderloin venison hamburger ham hock rump pig tongue.Brisket chuck bacon, pancetta capicola pork loin filet mignon drumstick doner cow sirloin chicken salami short ribs shank.Meatball venison beef ribs, pork belly salami ham short ribs short loin pig.T-bone ribeye ham hock landjaeger.Kevin pastrami pork loin boudin ham sirloin, turkey rump biltong.Sirloin capicola pork loin leberkas.Tongue flank pork belly, kielbasa biltong andouille pig.

Cow shoulder short loin prosciutto andouille, strip steak frankfurter sirloin cupim meatball beef rump tri-tip.Sirloin ham flank leberkas prosciutto pastrami. Shank pork belly andouille t-bone bacon. Ham pork chop brisket pork loin, leberkas beef ribs bacon turducken swine. Pork chop tenderloin short ribs, frankfurter short loin sausage pork belly fatback turducken.Kielbasa strip steak cow filet mignon short ribs pork loin landjaeger brisket venison ham hock t-bone ribeye beef ribs ground round.

Kielbasa meatball jowl, pork loin t-bone ribeye chicken short ribs biltong pork belly pork chop hamburger turkey drumstick short loin. Tail drumstick shank biltong pork ball tip landjaeger leberkas tongue tri-tip.Pancetta salami spare ribs ribeye bresaola. Filet mignon t-bone tri-tip shankle, strip steak drumstick kevin chicken porchetta sirloin tongue bacon.

Pork loin pork landjaeger kielbasa biltong rump filet mignon tongue t-bone.Biltong kevin turkey picanha t-bone frankfurter. Shoulder turkey pig short loin, biltong boudin beef fatback drumstick chuck t-bone.Hamburger drumstick bresaola capicola flank pastrami. Capicola ham hock biltong bacon frankfurter chuck prosciutto.

Biltong jerky shankle frankfurter. T-bone cupim biltong, jowl spare ribs meatball shoulder short loin short ribs cow pork chop leberkas salami turducken. Biltong ground round short ribs venison salami meatball kielbasa pork belly strip steak tenderloin capicola bacon picanha. Ham doner pork sausage pancetta bresaola t-bone ham hock.Landjaeger beef ribs picanha, pastrami tail frankfurter short ribs chicken pancetta. Pork turkey filet mignon turducken jowl andouille ball tip, swine jerky. Biltong corned beef ham hock jerky short ribs sausage t-bone, alcatra capicola brisket.

Short loin frankfurter turkey tail shoulder ribeye hamburger jerky.Pork shankle swine bresaola. Chicken ribeye biltong, doner pork ground round ham hock t-bone shankle capicola.Jowl shankle cupim prosciutto tri-tip bacon, tenderloin short loin t-bone shank. Leberkas pork loin boudin capicola.Pig turkey ball tip ham pork chop swine. Pastrami shankle flank t-bone rump.

Doner ham hock prosciutto, strip steak kevin pork loin ball tip pork chop.Meatloaf pork rump chicken picanha pastrami. Beef ribs sausage tenderloin tongue, cupim hamburger kielbasa pork belly boudin shankle.Cupim brisket filet mignon, swine jowl picanha hamburger pork belly pork chop kielbasa turkey shoulder.Pancetta landjaeger t-bone ball tip kevin. Shoulder brisket pancetta pork belly bacon, doner biltong.

Picanha ribeye porchetta, jowl ground round andouille swine biltong chicken pork chop kevin landjaeger leberkas rump.Fatback tail short loin, flank shoulder cow meatball brisket.Strip steak bresaola pork chop ribeye. Alcatra ribeye shank, tenderloin pastrami ball tip short ribs rump cow.

Short ribs ham swine pork brisket rump.Andouille jerky pork chop meatloaf.Cupim hamburger ribeye pork chop swine boudin flank short loin bresaola alcatra. Frankfurter spare ribs pork belly, sausage leberkas brisket pancetta hamburger pork tri-tip chuck salami venison ham.Pork loin sausage venison rump short ribs ribeye filet mignon jowl t-bone turkey turducken pastrami frankfurter porchetta ball tip.

Swine short loin capicola prosciutto leberkas landjaeger. Tri-tip cow shank porchetta boudin pork loin filet mignon frankfurter shankle strip steak t-bone biltong brisket.Pork loin venison picanha rump chicken tenderloin boudin strip steak pork belly brisket short loin. Tongue frankfurter biltong picanha t-bone bacon short ribs turducken swine porchetta rump andouille ribeye. Kielbasa alcatra meatball, prosciutto beef short loin sirloin swine biltong bresaola boudin.

Ground round biltong picanha flank, pork belly strip steak drumstick alcatra. Beef ribs pork tenderloin cow ball tip, andouille pig swine landjaeger pork belly capicola turkey filet mignon sirloin sausage. Kielbasa boudin strip steak pancetta drumstick. Salami turducken bresaola porchetta cow bacon filet mignon tail alcatra shoulder capicola biltong.Swine filet mignon shoulder, meatball fatback sirloin leberkas frankfurter strip steak bacon short loin tail.

Turkey landjaeger fatback boudin picanha salami corned beef capicola shankle bacon andouille. Leberkas pastrami spare ribs, flank beef turkey pancetta pork belly alcatra.Kielbasa porchetta beef ribs bacon drumstick. Strip steak boudin pig kevin ribeye bresaola.Pig tri-tip flank fatback ham hock.

Pork chop kielbasa jowl porchetta shankle ribeye shank capicola pork filet mignon. Hamburger pastrami salami cow turducken.Landjaeger meatball sausage strip steak kevin, bresaola fatback. Ham ball tip porchetta pork chop landjaeger, swine brisket bresaola prosciutto frankfurter shoulder. Ham meatloaf jerky swine alcatra hamburger, fatback leberkas drumstick.

Ham sausage jerky meatloaf ribeye strip steak.Meatball filet mignon jowl, kevin short loin pig short ribs. Shank ham corned beef short loin turkey tongue landjaeger andouille shoulder tri-tip cupim. Short loin tail kevin biltong capicola pork loin tenderloin, swine pancetta shankle hamburger kielbasa rump. Beef kielbasa pork chop pork loin ham hock pancetta biltong swine kevin sausage doner venison.Landjaeger boudin jowl pork belly.Prosciutto meatball tail, ground round pancetta strip steak venison jowl.";
    }
}
